//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikePOS.Resx
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HikePOS.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string HumbergerMenuIconUnicode
        {
            get
            {
                return ResourceManager.GetString("HumbergerMenuIconUnicode", resourceCulture);
            }
        }

        internal static string BackIconUnicode
        {
            get
            {
                return ResourceManager.GetString("BackIconUnicode", resourceCulture);
            }
        }

        internal static string CloseIconUnicode
        {
            get
            {
                return ResourceManager.GetString("CloseIconUnicode", resourceCulture);
            }
        }

        internal static string StarBorderIconUnicode
        {
            get
            {
                return ResourceManager.GetString("StarBorderIconUnicode", resourceCulture);
            }
        }

        internal static string StarIconUnicode
        {
            get
            {
                return ResourceManager.GetString("StarIconUnicode", resourceCulture);
            }
        }

        internal static string CheckBoxIconUnicode
        {
            get
            {
                return ResourceManager.GetString("CheckBoxIconUnicode", resourceCulture);
            }
        }

        internal static string UnCheckBoxIconUnicode
        {
            get
            {
                return ResourceManager.GetString("UnCheckBoxIconUnicode", resourceCulture);
            }
        }

        internal static string BookmarkIconUnicode
        {
            get
            {
                return ResourceManager.GetString("BookmarkIconUnicode", resourceCulture);
            }
        }

        internal static string GiftIconUnicode
        {
            get
            {
                return ResourceManager.GetString("GiftIconUnicode", resourceCulture);
            }
        }

        internal static string TrashIconUnicode
        {
            get
            {
                return ResourceManager.GetString("TrashIconUnicode", resourceCulture);
            }
        }

        internal static string EditIconUnicode
        {
            get
            {
                return ResourceManager.GetString("EditIconUnicode", resourceCulture);
            }
        }

        internal static string FolderIconUnicode
        {
            get
            {
                return ResourceManager.GetString("FolderIconUnicode", resourceCulture);
            }
        }

        internal static string FilterIconUnicode
        {
            get
            {
                return ResourceManager.GetString("FilterIconUnicode", resourceCulture);
            }
        }

        internal static string CalculatorIconUnicode
        {
            get
            {
                return ResourceManager.GetString("CalculatorIconUnicode", resourceCulture);
            }
        }

        internal static string CheckIconUnicode
        {
            get
            {
                return ResourceManager.GetString("CheckIconUnicode", resourceCulture);
            }
        }

        internal static string WindowCloseIconUnicode
        {
            get
            {
                return ResourceManager.GetString("WindowCloseIconUnicode", resourceCulture);
            }
        }

        internal static string StoreName_Placeholder
        {
            get
            {
                return ResourceManager.GetString("StoreName_Placeholder", resourceCulture);
            }
        }

        internal static string StoreName_InValidMessage
        {
            get
            {
                return ResourceManager.GetString("StoreName_InValidMessage", resourceCulture);
            }
        }

        internal static string StoreName_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("StoreName_EmptyMessage", resourceCulture);
            }
        }

        internal static string StoreName_LabelText
        {
            get
            {
                return ResourceManager.GetString("StoreName_LabelText", resourceCulture);
            }
        }

        internal static string Email_Placeholder
        {
            get
            {
                return ResourceManager.GetString("Email_Placeholder", resourceCulture);
            }
        }

        internal static string Email_InValidMessage
        {
            get
            {
                return ResourceManager.GetString("Email_InValidMessage", resourceCulture);
            }
        }

        internal static string Email_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("Email_EmptyMessage", resourceCulture);
            }
        }

        internal static string Password_Placeholder
        {
            get
            {
                return ResourceManager.GetString("Password_Placeholder", resourceCulture);
            }
        }

        internal static string Password_InValidMessage
        {
            get
            {
                return ResourceManager.GetString("Password_InValidMessage", resourceCulture);
            }
        }

        internal static string Password_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("Password_EmptyMessage", resourceCulture);
            }
        }

        internal static string Login_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Login_ButtonText", resourceCulture);
            }
        }

        internal static string Signup_LabelText
        {
            get
            {
                return ResourceManager.GetString("Signup_LabelText", resourceCulture);
            }
        }

        internal static string Register_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Register_ButtonText", resourceCulture);
            }
        }

        internal static string Forgot_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Forgot_ButtonText", resourceCulture);
            }
        }

        internal static string DiscountPopupTitle
        {
            get
            {
                return ResourceManager.GetString("DiscountPopupTitle", resourceCulture);
            }
        }

        internal static string TipPopupTitle
        {
            get
            {
                return ResourceManager.GetString("TipPopupTitle", resourceCulture);
            }
        }

        internal static string StoreNameAlreadyExistsMessage
        {
            get
            {
                return ResourceManager.GetString("StoreNameAlreadyExistsMessage", resourceCulture);
            }
        }

        internal static string Signup_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Signup_ButtonText", resourceCulture);
            }
        }

        internal static string Already_LabelText
        {
            get
            {
                return ResourceManager.GetString("Already_LabelText", resourceCulture);
            }
        }

        internal static string Forgot_TitleText
        {
            get
            {
                return ResourceManager.GetString("Forgot_TitleText", resourceCulture);
            }
        }

        internal static string Submit_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Submit_ButtonText", resourceCulture);
            }
        }

        internal static string Remember_LabelText
        {
            get
            {
                return ResourceManager.GetString("Remember_LabelText", resourceCulture);
            }
        }

        internal static string SendResetPasswordSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("SendResetPasswordSuccessMessage", resourceCulture);
            }
        }

        internal static string Logout_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Logout_ButtonText", resourceCulture);
            }
        }

        internal static string ChangeUser_ButtonText
        {
            get
            {
                return ResourceManager.GetString("ChangeUser_ButtonText", resourceCulture);
            }
        }

        internal static string CloseRegister_ButtonText
        {
            get
            {
                return ResourceManager.GetString("CloseRegister_ButtonText", resourceCulture);
            }
        }

        internal static string ChangePassword_ButtonText
        {
            get
            {
                return ResourceManager.GetString("ChangePassword_ButtonText", resourceCulture);
            }
        }

        internal static string EnterSale_TitleText
        {
            get
            {
                return ResourceManager.GetString("EnterSale_TitleText", resourceCulture);
            }
        }

        internal static string SaleHistory_TitleText
        {
            get
            {
                return ResourceManager.GetString("SaleHistory_TitleText", resourceCulture);
            }
        }

        internal static string CashRegister_TitileText
        {
            get
            {
                return ResourceManager.GetString("CashRegister_TitileText", resourceCulture);
            }
        }

        internal static string Settings_TitleText
        {
            get
            {
                return ResourceManager.GetString("Settings_TitleText", resourceCulture);
            }
        }

        internal static string Admin_TitleText
        {
            get
            {
                return ResourceManager.GetString("Admin_TitleText", resourceCulture);
            }
        }

        internal static string Payment_TitleText
        {
            get
            {
                return ResourceManager.GetString("Payment_TitleText", resourceCulture);
            }
        }

        internal static string CustomSale_TitleText
        {
            get
            {
                return ResourceManager.GetString("CustomSale_TitleText", resourceCulture);
            }
        }

        internal static string Intercom_TitleText
        {
            get
            {
                return ResourceManager.GetString("Intercom_TitleText", resourceCulture);
            }
        }

        internal static string Online_Text
        {
            get
            {
                return ResourceManager.GetString("Online_Text", resourceCulture);
            }
        }

        internal static string Offline_Text
        {
            get
            {
                return ResourceManager.GetString("Offline_Text", resourceCulture);
            }
        }

        internal static string Connected_Text
        {
            get
            {
                return ResourceManager.GetString("Connected_Text", resourceCulture);
            }
        }

        internal static string NotFound_Text
        {
            get
            {
                return ResourceManager.GetString("NotFound_Text", resourceCulture);
            }
        }

        internal static string AutoLock_EmptyPinText
        {
            get
            {
                return ResourceManager.GetString("AutoLock_EmptyPinText", resourceCulture);
            }
        }

        internal static string AutoLock_4DigitPasscodeText
        {
            get
            {
                return ResourceManager.GetString("AutoLock_4DigitPasscodeText", resourceCulture);
            }
        }

        internal static string SelectRegister_TitleText
        {
            get
            {
                return ResourceManager.GetString("SelectRegister_TitleText", resourceCulture);
            }
        }

        internal static string Progress0_Text
        {
            get
            {
                return ResourceManager.GetString("Progress0_Text", resourceCulture);
            }
        }

        internal static string Progress1_Text
        {
            get
            {
                return ResourceManager.GetString("Progress1_Text", resourceCulture);
            }
        }

        internal static string Progress2_Text
        {
            get
            {
                return ResourceManager.GetString("Progress2_Text", resourceCulture);
            }
        }

        internal static string Progress3_Text
        {
            get
            {
                return ResourceManager.GetString("Progress3_Text", resourceCulture);
            }
        }

        internal static string Progress4_Text
        {
            get
            {
                return ResourceManager.GetString("Progress4_Text", resourceCulture);
            }
        }

        internal static string Progress5_Text
        {
            get
            {
                return ResourceManager.GetString("Progress5_Text", resourceCulture);
            }
        }

        internal static string Progress6_Text
        {
            get
            {
                return ResourceManager.GetString("Progress6_Text", resourceCulture);
            }
        }

        internal static string Progress7_Text
        {
            get
            {
                return ResourceManager.GetString("Progress7_Text", resourceCulture);
            }
        }

        internal static string Progress8_Text
        {
            get
            {
                return ResourceManager.GetString("Progress8_Text", resourceCulture);
            }
        }

        internal static string Progress9_Text
        {
            get
            {
                return ResourceManager.GetString("Progress9_Text", resourceCulture);
            }
        }

        internal static string Progress10_Text
        {
            get
            {
                return ResourceManager.GetString("Progress10_Text", resourceCulture);
            }
        }

        internal static string SearchProduct_PlaceHolder
        {
            get
            {
                return ResourceManager.GetString("SearchProduct_PlaceHolder", resourceCulture);
            }
        }

        internal static string PayButtonText
        {
            get
            {
                return ResourceManager.GetString("PayButtonText", resourceCulture);
            }
        }

        internal static string OfferTitle
        {
            get
            {
                return ResourceManager.GetString("OfferTitle", resourceCulture);
            }
        }

        internal static string Price_Placeholder
        {
            get
            {
                return ResourceManager.GetString("Price_Placeholder", resourceCulture);
            }
        }

        internal static string Discount_Placeholder
        {
            get
            {
                return ResourceManager.GetString("Discount_Placeholder", resourceCulture);
            }
        }

        internal static string CustomSale_Placeholder
        {
            get
            {
                return ResourceManager.GetString("CustomSale_Placeholder", resourceCulture);
            }
        }

        internal static string Save_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Save_ButtonText", resourceCulture);
            }
        }

        internal static string Edit_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Edit_ButtonText", resourceCulture);
            }
        }

        internal static string Info_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Info_ButtonText", resourceCulture);
            }
        }

        internal static string Back_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Back_ButtonText", resourceCulture);
            }
        }

        internal static string Verify_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Verify_ButtonText", resourceCulture);
            }
        }

        internal static string AddToCart_ButtonText
        {
            get
            {
                return ResourceManager.GetString("AddToCart_ButtonText", resourceCulture);
            }
        }

        internal static string GiftCard_Placeholder
        {
            get
            {
                return ResourceManager.GetString("GiftCard_Placeholder", resourceCulture);
            }
        }

        internal static string GiftCardAmount_Placeholder
        {
            get
            {
                return ResourceManager.GetString("GiftCardAmount_Placeholder", resourceCulture);
            }
        }

        internal static string ProductDetailHeader
        {
            get
            {
                return ResourceManager.GetString("ProductDetailHeader", resourceCulture);
            }
        }

        internal static string IncreaseRefundProductQuantityValidationMessage
        {
            get
            {
                return ResourceManager.GetString("IncreaseRefundProductQuantityValidationMessage", resourceCulture);
            }
        }

        internal static string DecreaseSaleProductQuantityValidationMessage
        {
            get
            {
                return ResourceManager.GetString("DecreaseSaleProductQuantityValidationMessage", resourceCulture);
            }
        }

        internal static string AddToPurchaseButtonText
        {
            get
            {
                return ResourceManager.GetString("AddToPurchaseButtonText", resourceCulture);
            }
        }

        internal static string PaypalEVMTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("PaypalEVMTransactionHeader", resourceCulture);
            }
        }

        internal static string ChargeButtonText
        {
            get
            {
                return ResourceManager.GetString("ChargeButtonText", resourceCulture);
            }
        }

        internal static string UpdateReaderButtonText
        {
            get
            {
                return ResourceManager.GetString("UpdateReaderButtonText", resourceCulture);
            }
        }

        internal static string ReadyToPayHeaderText
        {
            get
            {
                return ResourceManager.GetString("ReadyToPayHeaderText", resourceCulture);
            }
        }

        internal static string NoReaderFoundMessage
        {
            get
            {
                return ResourceManager.GetString("NoReaderFoundMessage", resourceCulture);
            }
        }

        internal static string TyroPurchaseTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("TyroPurchaseTransactionHeader", resourceCulture);
            }
        }

        internal static string iZettlePurchaseTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("iZettlePurchaseTransactionHeader", resourceCulture);
            }
        }

        internal static string MintTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("MintTransactionHeader", resourceCulture);
            }
        }

        internal static string AmountText
        {
            get
            {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }

        internal static string TyroTerminalConfigurationRequired
        {
            get
            {
                return ResourceManager.GetString("TyroTerminalConfigurationRequired", resourceCulture);
            }
        }

        internal static string MintConfigurationRequired
        {
            get
            {
                return ResourceManager.GetString("MintConfigurationRequired", resourceCulture);
            }
        }

        internal static string MintConfigurations
        {
            get
            {
                return ResourceManager.GetString("MintConfigurations", resourceCulture);
            }
        }

        internal static string AmountValidationForIntegratedPaymentTypeMessage
        {
            get
            {
                return ResourceManager.GetString("AmountValidationForIntegratedPaymentTypeMessage", resourceCulture);
            }
        }

        internal static string VantivConfigurations
        {
            get
            {
                return ResourceManager.GetString("VantivConfigurations", resourceCulture);
            }
        }

        internal static string AssemblyPaymentConfigurations
        {
            get
            {
                return ResourceManager.GetString("AssemblyPaymentConfigurations", resourceCulture);
            }
        }

        internal static string Configure_ButtonText
        {
            get
            {
                return ResourceManager.GetString("Configure_ButtonText", resourceCulture);
            }
        }

        internal static string CustomerAddButtonText
        {
            get
            {
                return ResourceManager.GetString("CustomerAddButtonText", resourceCulture);
            }
        }

        internal static string SearchCustomerPlaceholderText
        {
            get
            {
                return ResourceManager.GetString("SearchCustomerPlaceholderText", resourceCulture);
            }
        }

        internal static string Please_Select_LabelText
        {
            get
            {
                return ResourceManager.GetString("Please_Select_LabelText", resourceCulture);
            }
        }

        internal static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        internal static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        internal static string Gender
        {
            get
            {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        internal static string Birthdate
        {
            get
            {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }

        internal static string CompanyName
        {
            get
            {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }

        internal static string CustomerGroup
        {
            get
            {
                return ResourceManager.GetString("CustomerGroup", resourceCulture);
            }
        }

        internal static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        internal static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        internal static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        internal static string StreetAddress
        {
            get
            {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }

        internal static string State
        {
            get
            {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        internal static string Zip
        {
            get
            {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }

        internal static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        internal static string CustomerCode
        {
            get
            {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }

        internal static string CreditLimit
        {
            get
            {
                return ResourceManager.GetString("CreditLimit", resourceCulture);
            }
        }

        internal static string HowDidYouHearAboutUs
        {
            get
            {
                return ResourceManager.GetString("HowDidYouHearAboutUs", resourceCulture);
            }
        }

        internal static string Notes
        {
            get
            {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        internal static string CustomerSince
        {
            get
            {
                return ResourceManager.GetString("CustomerSince", resourceCulture);
            }
        }

        internal static string ValidAmount
        {
            get
            {
                return ResourceManager.GetString("ValidAmount", resourceCulture);
            }
        }

        internal static string ValidTenderAmount
        {
            get
            {
                return ResourceManager.GetString("ValidTenderAmount", resourceCulture);
            }
        }

        internal static string PRINTER_TYPE_POWA_POS
        {
            get
            {
                return ResourceManager.GetString("PRINTER_TYPE_POWA_POS", resourceCulture);
            }
        }

        internal static string Error_Title
        {
            get
            {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }

        internal static string Warning_Title
        {
            get
            {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }

        internal static string Authentication_Error_Title
        {
            get
            {
                return ResourceManager.GetString("Authentication_Error_Title", resourceCulture);
            }
        }

        internal static string AddGiftCard_Title
        {
            get
            {
                return ResourceManager.GetString("AddGiftCard_Title", resourceCulture);
            }
        }

        internal static string AddGiftCardNumber
        {
            get
            {
                return ResourceManager.GetString("AddGiftCardNumber", resourceCulture);
            }
        }

        internal static string AddGiftCardEnterAmount
        {
            get
            {
                return ResourceManager.GetString("AddGiftCardEnterAmount", resourceCulture);
            }
        }

        internal static string AddGiftCardBalance
        {
            get
            {
                return ResourceManager.GetString("AddGiftCardBalance", resourceCulture);
            }
        }

        internal static string AddCustomer_Title
        {
            get
            {
                return ResourceManager.GetString("AddCustomer_Title", resourceCulture);
            }
        }

        internal static string Server_Error_Title
        {
            get
            {
                return ResourceManager.GetString("Server_Error_Title", resourceCulture);
            }
        }

        internal static string SomethingWrong
        {
            get
            {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }

        internal static string NoInternetMessage
        {
            get
            {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }

        internal static string FirstNameRequiredValidationMessage
        {
            get
            {
                return ResourceManager.GetString("FirstNameRequiredValidationMessage", resourceCulture);
            }
        }

        internal static string GiftCardAmountValidationMessage
        {
            get
            {
                return ResourceManager.GetString("GiftCardAmountValidationMessage", resourceCulture);
            }
        }

        internal static string GiftCardNotAvailableValidationMessage
        {
            get
            {
                return ResourceManager.GetString("GiftCardNotAvailableValidationMessage", resourceCulture);
            }
        }

        internal static string GiftCardNumberValidationMessage
        {
            get
            {
                return ResourceManager.GetString("GiftCardNumberValidationMessage", resourceCulture);
            }
        }

        internal static string GiftCardNumberMinimumValidationMessage
        {
            get
            {
                return ResourceManager.GetString("GiftCardNumberMinimumValidationMessage", resourceCulture);
            }
        }

        internal static string BalanceLabelText
        {
            get
            {
                return ResourceManager.GetString("BalanceLabelText", resourceCulture);
            }
        }

        internal static string GiftCardBalanceValidationMessage
        {
            get
            {
                return ResourceManager.GetString("GiftCardBalanceValidationMessage", resourceCulture);
            }
        }

        internal static string PrinterValidationMessage
        {
            get
            {
                return ResourceManager.GetString("PrinterValidationMessage", resourceCulture);
            }
        }

        internal static string PrinterSelectionValidationMessage
        {
            get
            {
                return ResourceManager.GetString("PrinterSelectionValidationMessage", resourceCulture);
            }
        }

        internal static string CustomSaleNameValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CustomSaleNameValidationMessage", resourceCulture);
            }
        }

        internal static string CustomSaleQuantityValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CustomSaleQuantityValidationMessage", resourceCulture);
            }
        }

        internal static string NoItemBarcodeMessage
        {
            get
            {
                return ResourceManager.GetString("NoItemBarcodeMessage", resourceCulture);
            }
        }

        internal static string NoInvoiceItemBarcodeMessage
        {
            get
            {
                return ResourceManager.GetString("NoInvoiceItemBarcodeMessage", resourceCulture);
            }
        }

        internal static string ExtraProductSelectionValidationMessage
        {
            get
            {
                return ResourceManager.GetString("ExtraProductSelectionValidationMessage", resourceCulture);
            }
        }

        internal static string OutofStockMessage
        {
            get
            {
                return ResourceManager.GetString("OutofStockMessage", resourceCulture);
            }
        }

        internal static string CompositeOutofStockMessage
        {
            get
            {
                return ResourceManager.GetString("CompositeOutofStockMessage", resourceCulture);
            }
        }

        internal static string DiscountValidationMessage
        {
            get
            {
                return ResourceManager.GetString("DiscountValidationMessage", resourceCulture);
            }
        }

        internal static string TipValidationMessage
        {
            get
            {
                return ResourceManager.GetString("TipValidationMessage", resourceCulture);
            }
        }

        internal static string BackOrderCutomerValidation
        {
            get
            {
                return ResourceManager.GetString("BackOrderCutomerValidation", resourceCulture);
            }
        }

        internal static string PayButtonCutomerValidation
        {
            get
            {
                return ResourceManager.GetString("PayButtonCutomerValidation", resourceCulture);
            }
        }

        internal static string NoItemInStockMessage
        {
            get
            {
                return ResourceManager.GetString("NoItemInStockMessage", resourceCulture);
            }
        }

        internal static string RefundInternetValidationMessage
        {
            get
            {
                return ResourceManager.GetString("RefundInternetValidationMessage", resourceCulture);
            }
        }

        internal static string RefundSyncValidationMessage
        {
            get
            {
                return ResourceManager.GetString("RefundSyncValidationMessage", resourceCulture);
            }
        }

        internal static string RemovePaymentInCloseRegisterAlertMessage
        {
            get
            {
                return ResourceManager.GetString("RemovePaymentInCloseRegisterAlertMessage", resourceCulture);
            }
        }

        internal static string EnterSaleNoPermissionMessage
        {
            get
            {
                return ResourceManager.GetString("EnterSaleNoPermissionMessage", resourceCulture);
            }
        }

        internal static string CreditBalanceValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CreditBalanceValidationMessage", resourceCulture);
            }
        }

        internal static string CreditLimitValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CreditLimitValidationMessage", resourceCulture);
            }
        }

        internal static string LoyaltyLimitValidationMessage
        {
            get
            {
                return ResourceManager.GetString("LoyaltyLimitValidationMessage", resourceCulture);
            }
        }

        internal static string iZettleRefundMessage
        {
            get
            {
                return ResourceManager.GetString("iZettleRefundMessage", resourceCulture);
            }
        }

        internal static string PaypalLoginMessage
        {
            get
            {
                return ResourceManager.GetString("PaypalLoginMessage", resourceCulture);
            }
        }

        internal static string PaypalRefundMessage
        {
            get
            {
                return ResourceManager.GetString("PaypalRefundMessage", resourceCulture);
            }
        }

        internal static string MintRefundMessage
        {
            get
            {
                return ResourceManager.GetString("MintRefundMessage", resourceCulture);
            }
        }

        internal static string NumberValidationMessage
        {
            get
            {
                return ResourceManager.GetString("NumberValidationMessage", resourceCulture);
            }
        }

        internal static string SettingUpdateMessage
        {
            get
            {
                return ResourceManager.GetString("SettingUpdateMessage", resourceCulture);
            }
        }

        internal static string UpdateDataProccessMessage
        {
            get
            {
                return ResourceManager.GetString("UpdateDataProccessMessage", resourceCulture);
            }
        }

        internal static string NoFoundVariantProduct
        {
            get
            {
                return ResourceManager.GetString("NoFoundVariantProduct", resourceCulture);
            }
        }

        internal static string RemoveCreditPaymentMessage
        {
            get
            {
                return ResourceManager.GetString("RemoveCreditPaymentMessage", resourceCulture);
            }
        }

        internal static string CloseRegisterSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("CloseRegisterSuccessMessage", resourceCulture);
            }
        }

        internal static string CloseRegisterLoadDataErrorMessage
        {
            get
            {
                return ResourceManager.GetString("CloseRegisterLoadDataErrorMessage", resourceCulture);
            }
        }

        internal static string AlreadyOpenRegisterErrorMessage
        {
            get
            {
                return ResourceManager.GetString("AlreadyOpenRegisterErrorMessage", resourceCulture);
            }
        }

        internal static string EmailSendWaiting
        {
            get
            {
                return ResourceManager.GetString("EmailSendWaiting", resourceCulture);
            }
        }

        internal static string EmailSuccess
        {
            get
            {
                return ResourceManager.GetString("EmailSuccess", resourceCulture);
            }
        }

        internal static string EmailFailed
        {
            get
            {
                return ResourceManager.GetString("EmailFailed", resourceCulture);
            }
        }

        internal static string DataSyncSuccess
        {
            get
            {
                return ResourceManager.GetString("DataSyncSuccess", resourceCulture);
            }
        }

        internal static string ExpireMessage
        {
            get
            {
                return ResourceManager.GetString("ExpireMessage", resourceCulture);
            }
        }

        internal static string SubscriptionExntendedMessage
        {
            get
            {
                return ResourceManager.GetString("SubscriptionExntendedMessage", resourceCulture);
            }
        }

        internal static string SubscriptionIsOnHoldMessage
        {
            get
            {
                return ResourceManager.GetString("SubscriptionIsOnHoldMessage", resourceCulture);
            }
        }

        internal static string DataSyncContinueMessage
        {
            get
            {
                return ResourceManager.GetString("DataSyncContinueMessage", resourceCulture);
            }
        }

        internal static string RemovePaymentAleartMessage
        {
            get
            {
                return ResourceManager.GetString("RemovePaymentAleartMessage", resourceCulture);
            }
        }

        internal static string ResetAleartMessage
        {
            get
            {
                return ResourceManager.GetString("ResetAleartMessage", resourceCulture);
            }
        }

        internal static string EnableInvoicePrintReceiptText
        {
            get
            {
                return ResourceManager.GetString("EnableInvoicePrintReceiptText", resourceCulture);
            }
        }

        internal static string EnableDocketPrintReceiptText
        {
            get
            {
                return ResourceManager.GetString("EnableDocketPrintReceiptText", resourceCulture);
            }
        }

        internal static string EnableCustomerPrintReceiptText
        {
            get
            {
                return ResourceManager.GetString("EnableCustomerPrintReceiptText", resourceCulture);
            }
        }

        internal static string LoadUpdateDataHeaderText
        {
            get
            {
                return ResourceManager.GetString("LoadUpdateDataHeaderText", resourceCulture);
            }
        }

        internal static string LoadUpdateDataText
        {
            get
            {
                return ResourceManager.GetString("LoadUpdateDataText", resourceCulture);
            }
        }

        internal static string Migration
        {
            get
            {
                return ResourceManager.GetString("Migration", resourceCulture);
            }
        }

        internal static string Import
        {
            get
            {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }

        internal static string HikeEcommers
        {
            get
            {
                return ResourceManager.GetString("HikeEcommers", resourceCulture);
            }
        }

        internal static string iPad
        {
            get
            {
                return ResourceManager.GetString("iPad", resourceCulture);
            }
        }

        internal static string QB
        {
            get
            {
                return ResourceManager.GetString("QB", resourceCulture);
            }
        }

        internal static string Web
        {
            get
            {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }

        internal static string Woo
        {
            get
            {
                return ResourceManager.GetString("Woo", resourceCulture);
            }
        }

        internal static string BigCommerce
        {
            get
            {
                return ResourceManager.GetString("BigCommerce", resourceCulture);
            }
        }

        internal static string Shopify
        {
            get
            {
                return ResourceManager.GetString("Shopify", resourceCulture);
            }
        }

        internal static string Xero
        {
            get
            {
                return ResourceManager.GetString("Xero", resourceCulture);
            }
        }

        internal static string Magento
        {
            get
            {
                return ResourceManager.GetString("Magento", resourceCulture);
            }
        }

        internal static string ePages
        {
            get
            {
                return ResourceManager.GetString("ePages", resourceCulture);
            }
        }

        internal static string GeneralButtonText
        {
            get
            {
                return ResourceManager.GetString("GeneralButtonText", resourceCulture);
            }
        }

        internal static string PrinterButtonText
        {
            get
            {
                return ResourceManager.GetString("PrinterButtonText", resourceCulture);
            }
        }

        internal static string PaymentButtonText
        {
            get
            {
                return ResourceManager.GetString("PaymentButtonText", resourceCulture);
            }
        }

        internal static string MarkPaidOrderOptionLabelText
        {
            get
            {
                return ResourceManager.GetString("MarkPaidOrderOptionLabelText", resourceCulture);
            }
        }

        internal static string MarkPaidOrderOptionDescriptionText
        {
            get
            {
                return ResourceManager.GetString("MarkPaidOrderOptionDescriptionText", resourceCulture);
            }
        }

        internal static string AutoLockOptionLabelText
        {
            get
            {
                return ResourceManager.GetString("AutoLockOptionLabelText", resourceCulture);
            }
        }

        internal static string AutoLockOptionDescriptionText
        {
            get
            {
                return ResourceManager.GetString("AutoLockOptionDescriptionText", resourceCulture);
            }
        }

        internal static string SyncDataOptionLabelText
        {
            get
            {
                return ResourceManager.GetString("SyncDataOptionLabelText", resourceCulture);
            }
        }

        internal static string SyncDataOptionDescriptionText
        {
            get
            {
                return ResourceManager.GetString("SyncDataOptionDescriptionText", resourceCulture);
            }
        }

        internal static string SyncDataButtonText
        {
            get
            {
                return ResourceManager.GetString("SyncDataButtonText", resourceCulture);
            }
        }

        internal static string ClearSyncDataOptionLabelText
        {
            get
            {
                return ResourceManager.GetString("ClearSyncDataOptionLabelText", resourceCulture);
            }
        }

        internal static string ClearSyncDataOptionDescriptionText
        {
            get
            {
                return ResourceManager.GetString("ClearSyncDataOptionDescriptionText", resourceCulture);
            }
        }

        internal static string ClearSyncDataButtonText
        {
            get
            {
                return ResourceManager.GetString("ClearSyncDataButtonText", resourceCulture);
            }
        }

        internal static string PrimaryReceiptPrinterLabelText
        {
            get
            {
                return ResourceManager.GetString("PrimaryReceiptPrinterLabelText", resourceCulture);
            }
        }

        internal static string UseInHikeLabelText
        {
            get
            {
                return ResourceManager.GetString("UseInHikeLabelText", resourceCulture);
            }
        }

        internal static string DocketPrinterLabelText
        {
            get
            {
                return ResourceManager.GetString("DocketPrinterLabelText", resourceCulture);
            }
        }

        internal static string PrimaryDocketDescriptionText
        {
            get
            {
                return ResourceManager.GetString("PrimaryDocketDescriptionText", resourceCulture);
            }
        }

        internal static string NoOfCopiesLabelText
        {
            get
            {
                return ResourceManager.GetString("NoOfCopiesLabelText", resourceCulture);
            }
        }

        internal static string AutoPrintLabelText
        {
            get
            {
                return ResourceManager.GetString("AutoPrintLabelText", resourceCulture);
            }
        }

        internal static string EnableAutoOpenCashDrawerLabelText
        {
            get
            {
                return ResourceManager.GetString("EnableAutoOpenCashDrawerLabelText", resourceCulture);
            }
        }

        internal static string EnableAutoOpenCashDrawerOnlyCashSalesLabelText
        {
            get
            {
                return ResourceManager.GetString("EnableAutoOpenCashDrawerOnlyCashSalesLabelText", resourceCulture);
            }
        }

        internal static string AllCloudReceiptLabelText
        {
            get
            {
                return ResourceManager.GetString("AllCloudReceiptLabelText", resourceCulture);
            }
        }

        internal static string AllCloudReceiptDescriptionText
        {
            get
            {
                return ResourceManager.GetString("AllCloudReceiptDescriptionText", resourceCulture);
            }
        }

        internal static string AllCloudReceiptDescriptionLinkButtonText
        {
            get
            {
                return ResourceManager.GetString("AllCloudReceiptDescriptionLinkButtonText", resourceCulture);
            }
        }

        internal static string AllCloudReceiptQRCodeLabelText
        {
            get
            {
                return ResourceManager.GetString("AllCloudReceiptQRCodeLabelText", resourceCulture);
            }
        }

        internal static string AllCloudReceiptInfoLabelText
        {
            get
            {
                return ResourceManager.GetString("AllCloudReceiptInfoLabelText", resourceCulture);
            }
        }

        internal static string PaymentOptionDescriptionLabelText
        {
            get
            {
                return ResourceManager.GetString("PaymentOptionDescriptionLabelText", resourceCulture);
            }
        }

        internal static string IntegratedPaymentOptionDescriptionLabelText
        {
            get
            {
                return ResourceManager.GetString("IntegratedPaymentOptionDescriptionLabelText", resourceCulture);
            }
        }

        internal static string IntegratedPaymentOptionDescriptionLinkButtonText
        {
            get
            {
                return ResourceManager.GetString("IntegratedPaymentOptionDescriptionLinkButtonText", resourceCulture);
            }
        }

        internal static string Vantiv_Device_ISNot_Connected_Message
        {
            get
            {
                return ResourceManager.GetString("Vantiv_Device_ISNot_Connected_Message", resourceCulture);
            }
        }

        internal static string Vantiv_Device_IS_Connected_Message
        {
            get
            {
                return ResourceManager.GetString("Vantiv_Device_IS_Connected_Message", resourceCulture);
            }
        }

        internal static string VantivPurchaseTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("VantivPurchaseTransactionHeader", resourceCulture);
            }
        }

        internal static string VantivConfigurationMessage
        {
            get
            {
                return ResourceManager.GetString("VantivConfigurationMessage", resourceCulture);
            }
        }

        internal static string AssemblyPayment_Device_ISNot_Connected_Message
        {
            get
            {
                return ResourceManager.GetString("AssemblyPayment_Device_ISNot_Connected_Message", resourceCulture);
            }
        }

        internal static string AssemblyPayment_Device_IS_Connected_Message
        {
            get
            {
                return ResourceManager.GetString("AssemblyPayment_Device_IS_Connected_Message", resourceCulture);
            }
        }

        internal static string AssemblyPaymentPurchaseTransactionHeader
        {
            get
            {
                return ResourceManager.GetString("AssemblyPaymentPurchaseTransactionHeader", resourceCulture);
            }
        }

        internal static string AssemblyPaymentConfigurationMessage
        {
            get
            {
                return ResourceManager.GetString("AssemblyPaymentConfigurationMessage", resourceCulture);
            }
        }

        internal static string ClearBtnText
        {
            get
            {
                return ResourceManager.GetString("ClearBtnText", resourceCulture);
            }
        }

        internal static string AutolockPageTitle
        {
            get
            {
                return ResourceManager.GetString("AutolockPageTitle", resourceCulture);
            }
        }

        internal static string ActivePrinterLabelText
        {
            get
            {
                return ResourceManager.GetString("ActivePrinterLabelText", resourceCulture);
            }
        }

        internal static string ActivePrinterDescriptionLabelText
        {
            get
            {
                return ResourceManager.GetString("ActivePrinterDescriptionLabelText", resourceCulture);
            }
        }

        internal static string ActivePrinterDescriptionLinkButtonText
        {
            get
            {
                return ResourceManager.GetString("ActivePrinterDescriptionLinkButtonText", resourceCulture);
            }
        }

        internal static string PrinterCustomerQueueDocketLabelText
        {
            get
            {
                return ResourceManager.GetString("PrinterCustomerQueueDocketLabelText", resourceCulture);
            }
        }

        internal static string DocketNumberRangeLabelText
        {
            get
            {
                return ResourceManager.GetString("DocketNumberRangeLabelText", resourceCulture);
            }
        }

        internal static string CustomerDocketDescriptionLabelText
        {
            get
            {
                return ResourceManager.GetString("CustomerDocketDescriptionLabelText", resourceCulture);
            }
        }

        internal static string ConfigurationRequiredLabelText
        {
            get
            {
                return ResourceManager.GetString("ConfigurationRequiredLabelText", resourceCulture);
            }
        }

        internal static string ReadyToUseLabelText
        {
            get
            {
                return ResourceManager.GetString("ReadyToUseLabelText", resourceCulture);
            }
        }

        internal static string ChangePassword_TitleText
        {
            get
            {
                return ResourceManager.GetString("ChangePassword_TitleText", resourceCulture);
            }
        }

        internal static string CurrentPasswordText
        {
            get
            {
                return ResourceManager.GetString("CurrentPasswordText", resourceCulture);
            }
        }

        internal static string NewPasswordText
        {
            get
            {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }

        internal static string RepeatNewPasswordText
        {
            get
            {
                return ResourceManager.GetString("RepeatNewPasswordText", resourceCulture);
            }
        }

        internal static string AllValidationMessage
        {
            get
            {
                return ResourceManager.GetString("AllValidationMessage", resourceCulture);
            }
        }

        internal static string UserCurrentPassword_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("UserCurrentPassword_EmptyMessage", resourceCulture);
            }
        }

        internal static string UserNewPassword_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("UserNewPassword_EmptyMessage", resourceCulture);
            }
        }

        internal static string UserRepeatNewPassword_EmptyMessage
        {
            get
            {
                return ResourceManager.GetString("UserRepeatNewPassword_EmptyMessage", resourceCulture);
            }
        }

        internal static string UserPassword_InValidMessage
        {
            get
            {
                return ResourceManager.GetString("UserPassword_InValidMessage", resourceCulture);
            }
        }

        internal static string NewPasswordAndRepeatDidntMatchValidationMessage
        {
            get
            {
                return ResourceManager.GetString("NewPasswordAndRepeatDidntMatchValidationMessage", resourceCulture);
            }
        }

        internal static string ChangePasswordSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }

        internal static string ProductIsCurrentlyLockedMessage
        {
            get
            {
                return ResourceManager.GetString("ProductIsCurrentlyLockedMessage", resourceCulture);
            }
        }

        internal static string SignOutBtnText
        {
            get
            {
                return ResourceManager.GetString("SignOutBtnText", resourceCulture);
            }
        }

        internal static string ChangeUserPageTitle
        {
            get
            {
                return ResourceManager.GetString("ChangeUserPageTitle", resourceCulture);
            }
        }

        internal static string ForgotPasswordTitleText
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordTitleText", resourceCulture);
            }
        }

        internal static string SignUpPageTitleText
        {
            get
            {
                return ResourceManager.GetString("SignUpPageTitleText", resourceCulture);
            }
        }

        internal static string StartHike_Title
        {
            get
            {
                return ResourceManager.GetString("StartHike_Title", resourceCulture);
            }
        }

        internal static string SignupAndAgreementText1
        {
            get
            {
                return ResourceManager.GetString("SignupAndAgreementText1", resourceCulture);
            }
        }

        internal static string SignupAndAgreementText2
        {
            get
            {
                return ResourceManager.GetString("SignupAndAgreementText2", resourceCulture);
            }
        }

        internal static string SignupAndAgreementText3
        {
            get
            {
                return ResourceManager.GetString("SignupAndAgreementText3", resourceCulture);
            }
        }

        internal static string SignupAndAgreementText4
        {
            get
            {
                return ResourceManager.GetString("SignupAndAgreementText4", resourceCulture);
            }
        }

        internal static string AddSomeDemoProductsText
        {
            get
            {
                return ResourceManager.GetString("AddSomeDemoProductsText", resourceCulture);
            }
        }

        internal static string SummaryText
        {
            get
            {
                return ResourceManager.GetString("SummaryText", resourceCulture);
            }
        }

        internal static string PrintText
        {
            get
            {
                return ResourceManager.GetString("PrintText", resourceCulture);
            }
        }

        internal static string AddRemoveCashText
        {
            get
            {
                return ResourceManager.GetString("AddRemoveCashText", resourceCulture);
            }
        }

        internal static string CloseRegisterText
        {
            get
            {
                return ResourceManager.GetString("CloseRegisterText", resourceCulture);
            }
        }

        internal static string ResetDataText
        {
            get
            {
                return ResourceManager.GetString("ResetDataText", resourceCulture);
            }
        }

        internal static string ChangeRegisterOutletText
        {
            get
            {
                return ResourceManager.GetString("ChangeRegisterOutletText", resourceCulture);
            }
        }

        internal static string PaymentsText
        {
            get
            {
                return ResourceManager.GetString("PaymentsText", resourceCulture);
            }
        }

        internal static string TransactionsText
        {
            get
            {
                return ResourceManager.GetString("TransactionsText", resourceCulture);
            }
        }

        internal static string SalesText
        {
            get
            {
                return ResourceManager.GetString("SalesText", resourceCulture);
            }
        }

        internal static string PaymentsReceivedText
        {
            get
            {
                return ResourceManager.GetString("PaymentsReceivedText", resourceCulture);
            }
        }

        internal static string TaxCollectedText
        {
            get
            {
                return ResourceManager.GetString("TaxCollectedText", resourceCulture);
            }
        }

        internal static string DiscountsGivenText
        {
            get
            {
                return ResourceManager.GetString("DiscountsGivenText", resourceCulture);
            }
        }

        internal static string TipsSurchargeText
        {
            get
            {
                return ResourceManager.GetString("TipsSurchargeText", resourceCulture);
            }
        }

        internal static string RefundsText
        {
            get
            {
                return ResourceManager.GetString("RefundsText", resourceCulture);
            }
        }

        internal static string CashAddedRemovedText
        {
            get
            {
                return ResourceManager.GetString("CashAddedRemovedText", resourceCulture);
            }
        }

        internal static string ThisSaleAlreadyRefunded
        {
            get
            {
                return ResourceManager.GetString("ThisSaleAlreadyRefunded", resourceCulture);
            }
        }

        internal static string NoFoundSales
        {
            get
            {
                return ResourceManager.GetString("NoFoundSales", resourceCulture);
            }
        }

        internal static string AddOrRemoveCashText
        {
            get
            {
                return ResourceManager.GetString("AddOrRemoveCashText", resourceCulture);
            }
        }

        internal static string NoteText
        {
            get
            {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }

        internal static string RemoveCashText
        {
            get
            {
                return ResourceManager.GetString("RemoveCashText", resourceCulture);
            }
        }

        internal static string AddCashText
        {
            get
            {
                return ResourceManager.GetString("AddCashText", resourceCulture);
            }
        }

        internal static string AddCashInOutPageTitle
        {
            get
            {
                return ResourceManager.GetString("AddCashInOutPageTitle", resourceCulture);
            }
        }

        internal static string VerifyBalanceAndCloseRegisterText
        {
            get
            {
                return ResourceManager.GetString("VerifyBalanceAndCloseRegisterText", resourceCulture);
            }
        }

        internal static string PaymentTypeText
        {
            get
            {
                return ResourceManager.GetString("PaymentTypeText", resourceCulture);
            }
        }

        internal static string CountedText
        {
            get
            {
                return ResourceManager.GetString("CountedText", resourceCulture);
            }
        }

        internal static string ExpectedText
        {
            get
            {
                return ResourceManager.GetString("ExpectedText", resourceCulture);
            }
        }

        internal static string DifferenceText
        {
            get
            {
                return ResourceManager.GetString("DifferenceText", resourceCulture);
            }
        }

        internal static string OpenRegisterText
        {
            get
            {
                return ResourceManager.GetString("OpenRegisterText", resourceCulture);
            }
        }

        internal static string FloatingAmountText
        {
            get
            {
                return ResourceManager.GetString("FloatingAmountText", resourceCulture);
            }
        }

        internal static string FilterByStatusText
        {
            get
            {
                return ResourceManager.GetString("FilterByStatusText", resourceCulture);
            }
        }

        internal static string SalesHistoryText
        {
            get
            {
                return ResourceManager.GetString("SalesHistoryText", resourceCulture);
            }
        }

        internal static string SaleText
        {
            get
            {
                return ResourceManager.GetString("SaleText", resourceCulture);
            }
        }

        internal static string DateText
        {
            get
            {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }

        internal static string CustomerText
        {
            get
            {
                return ResourceManager.GetString("CustomerText", resourceCulture);
            }
        }

        internal static string SourceText
        {
            get
            {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }

        internal static string SaleTotalText
        {
            get
            {
                return ResourceManager.GetString("SaleTotalText", resourceCulture);
            }
        }

        internal static string StatusText
        {
            get
            {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }

        internal static string OutstandingText
        {
            get
            {
                return ResourceManager.GetString("OutstandingText", resourceCulture);
            }
        }

        internal static string FulfillmentStatusText
        {
            get
            {
                return ResourceManager.GetString("FulfillmentStatusText", resourceCulture);
            }
        }

        internal static string PaymentStatusText
        {
            get
            {
                return ResourceManager.GetString("PaymentStatusText", resourceCulture);
            }
        }

        internal static string AllText
        {
            get
            {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }

        internal static string LayByText
        {
            get
            {
                return ResourceManager.GetString("LayByText", resourceCulture);
            }
        }

        internal static string ParkedText
        {
            get
            {
                return ResourceManager.GetString("ParkedText", resourceCulture);
            }
        }

        internal static string VoidedText
        {
            get
            {
                return ResourceManager.GetString("VoidedText", resourceCulture);
            }
        }

        internal static string BackOrderText
        {
            get
            {
                return ResourceManager.GetString("BackOrderText", resourceCulture);
            }
        }

        internal static string OnAccountText
        {
            get
            {
                return ResourceManager.GetString("OnAccountText", resourceCulture);
            }
        }

        internal static string RefundedText
        {
            get
            {
                return ResourceManager.GetString("RefundedText", resourceCulture);
            }
        }

        internal static string CompletedText
        {
            get
            {
                return ResourceManager.GetString("CompletedText", resourceCulture);
            }
        }

        internal static string UnsyncText
        {
            get
            {
                return ResourceManager.GetString("UnsyncText", resourceCulture);
            }
        }

        internal static string OpenQuotes
        {
            get
            {
                return ResourceManager.GetString("OpenQuotes", resourceCulture);
            }
        }

        internal static string ClosedQuotes
        {
            get
            {
                return ResourceManager.GetString("ClosedQuotes", resourceCulture);
            }
        }

        internal static string VoidedQuotes
        {
            get
            {
                return ResourceManager.GetString("VoidedQuotes", resourceCulture);
            }
        }

        internal static string EmailText
        {
            get
            {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }

        internal static string GiftReceiptPrintText
        {
            get
            {
                return ResourceManager.GetString("GiftReceiptPrintText", resourceCulture);
            }
        }

        internal static string RefundText
        {
            get
            {
                return ResourceManager.GetString("RefundText", resourceCulture);
            }
        }

        internal static string ReopenText
        {
            get
            {
                return ResourceManager.GetString("ReopenText", resourceCulture);
            }
        }

        internal static string MarkAsCompleteText
        {
            get
            {
                return ResourceManager.GetString("MarkAsCompleteText", resourceCulture);
            }
        }

        internal static string SubtotalText
        {
            get
            {
                return ResourceManager.GetString("SubtotalText", resourceCulture);
            }
        }

        internal static string DiscountText
        {
            get
            {
                return ResourceManager.GetString("DiscountText", resourceCulture);
            }
        }

        internal static string TipText
        {
            get
            {
                return ResourceManager.GetString("TipText", resourceCulture);
            }
        }

        internal static string TotalText
        {
            get
            {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }

        internal static string PaidText
        {
            get
            {
                return ResourceManager.GetString("PaidText", resourceCulture);
            }
        }

        internal static string SelectCustomerText
        {
            get
            {
                return ResourceManager.GetString("SelectCustomerText", resourceCulture);
            }
        }

        internal static string TaxText
        {
            get
            {
                return ResourceManager.GetString("TaxText", resourceCulture);
            }
        }

        internal static string ToPayText
        {
            get
            {
                return ResourceManager.GetString("ToPayText", resourceCulture);
            }
        }

        internal static string AmountTenderedText
        {
            get
            {
                return ResourceManager.GetString("AmountTenderedText", resourceCulture);
            }
        }

        internal static string GiftCardText
        {
            get
            {
                return ResourceManager.GetString("GiftCardText", resourceCulture);
            }
        }

        internal static string ChargeText
        {
            get
            {
                return ResourceManager.GetString("ChargeText", resourceCulture);
            }
        }

        internal static string SavePartialyPaidText
        {
            get
            {
                return ResourceManager.GetString("SavePartialyPaidText", resourceCulture);
            }
        }

        internal static string IssueChangeText
        {
            get
            {
                return ResourceManager.GetString("IssueChangeText", resourceCulture);
            }
        }

        internal static string SellLaybyAlertTitle
        {
            get
            {
                return ResourceManager.GetString("SellLaybyAlertTitle", resourceCulture);
            }
        }

        internal static string SellLaybyAlertBody
        {
            get
            {
                return ResourceManager.GetString("SellLaybyAlertBody", resourceCulture);
            }
        }

        internal static string SellAccountAlertTitle
        {
            get
            {
                return ResourceManager.GetString("SellAccountAlertTitle", resourceCulture);
            }
        }

        internal static string SellAccountAlertBody
        {
            get
            {
                return ResourceManager.GetString("SellAccountAlertBody", resourceCulture);
            }
        }

        internal static string ParkedAlertTitle
        {
            get
            {
                return ResourceManager.GetString("ParkedAlertTitle", resourceCulture);
            }
        }

        internal static string ParkedAlertBody
        {
            get
            {
                return ResourceManager.GetString("ParkedAlertBody", resourceCulture);
            }
        }

        internal static string HasOrderFulfilled
        {
            get
            {
                return ResourceManager.GetString("HasOrderFulfilled", resourceCulture);
            }
        }

        internal static string FashionClothing
        {
            get
            {
                return ResourceManager.GetString("FashionClothing", resourceCulture);
            }
        }

        internal static string HomewareGift
        {
            get
            {
                return ResourceManager.GetString("HomewareGift", resourceCulture);
            }
        }

        internal static string CafeRestaurant
        {
            get
            {
                return ResourceManager.GetString("CafeRestaurant", resourceCulture);
            }
        }

        internal static string HairSalons
        {
            get
            {
                return ResourceManager.GetString("HairSalons", resourceCulture);
            }
        }

        internal static string FoodTruck
        {
            get
            {
                return ResourceManager.GetString("FoodTruck", resourceCulture);
            }
        }

        internal static string ToysHobbies
        {
            get
            {
                return ResourceManager.GetString("ToysHobbies", resourceCulture);
            }
        }

        internal static string ToolsHardware
        {
            get
            {
                return ResourceManager.GetString("ToolsHardware", resourceCulture);
            }
        }

        internal static string Other
        {
            get
            {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }

        internal static string StartingNewBusiness
        {
            get
            {
                return ResourceManager.GetString("StartingNewBusiness", resourceCulture);
            }
        }

        internal static string ExistingBusinessNewToCloudPOSSoftware
        {
            get
            {
                return ResourceManager.GetString("ExistingBusinessNewToCloudPOSSoftware", resourceCulture);
            }
        }

        internal static string LookingToSwitchPlatforms
        {
            get
            {
                return ResourceManager.GetString("LookingToSwitchPlatforms", resourceCulture);
            }
        }

        internal static string ResearchingForMyClient
        {
            get
            {
                return ResourceManager.GetString("ResearchingForMyClient", resourceCulture);
            }
        }

        internal static string ImJustPlayingAround
        {
            get
            {
                return ResourceManager.GetString("ImJustPlayingAround", resourceCulture);
            }
        }

        internal static string HikePartnerSettingItUpForClient
        {
            get
            {
                return ResourceManager.GetString("HikePartnerSettingItUpForClient", resourceCulture);
            }
        }

        internal static string ExistingCustomer
        {
            get
            {
                return ResourceManager.GetString("ExistingCustomer", resourceCulture);
            }
        }

        internal static string CustomerEmailAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("CustomerEmailAlreadyExist", resourceCulture);
            }
        }

        internal static string LastNameRequiredValidationMessage
        {
            get
            {
                return ResourceManager.GetString("LastNameRequiredValidationMessage", resourceCulture);
            }
        }

        internal static string CityRequiredValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CityRequiredValidationMessage", resourceCulture);
            }
        }

        internal static string ZipRequiredValidationMessage
        {
            get
            {
                return ResourceManager.GetString("ZipRequiredValidationMessage", resourceCulture);
            }
        }

        internal static string PhoneRequiredValidationMessage
        {
            get
            {
                return ResourceManager.GetString("PhoneRequiredValidationMessage", resourceCulture);
            }
        }

        internal static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        internal static string Yesterday
        {
            get
            {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }

        internal static string Last7Days
        {
            get
            {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }

        internal static string Last30Days
        {
            get
            {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }

        internal static string ThisMonth
        {
            get
            {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }

        internal static string LastMonth
        {
            get
            {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }

        internal static string CustomerNotFound
        {
            get
            {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }

        internal static string CancelButtonText
        {
            get
            {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }

        internal static string SaveButtonText
        {
            get
            {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }

        internal static string YesButtonText
        {
            get
            {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }

        internal static string InputBoxPlaceholder
        {
            get
            {
                return ResourceManager.GetString("InputBoxPlaceholder", resourceCulture);
            }
        }

        internal static string AddNotePlaceholder
        {
            get
            {
                return ResourceManager.GetString("AddNotePlaceholder", resourceCulture);
            }
        }

        internal static string UsernameLabel
        {
            get
            {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }

        internal static string UserpinLabel
        {
            get
            {
                return ResourceManager.GetString("UserpinLabel", resourceCulture);
            }
        }

        internal static string StatusLabel
        {
            get
            {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }

        internal static string UserNamePlaceholder
        {
            get
            {
                return ResourceManager.GetString("UserNamePlaceholder", resourceCulture);
            }
        }

        internal static string UserPINPlaceholder
        {
            get
            {
                return ResourceManager.GetString("UserPINPlaceholder", resourceCulture);
            }
        }

        internal static string AcceptorIdLabel
        {
            get
            {
                return ResourceManager.GetString("AcceptorIdLabel", resourceCulture);
            }
        }

        internal static string AcceptorIdPlaceholder
        {
            get
            {
                return ResourceManager.GetString("AcceptorIdPlaceholder", resourceCulture);
            }
        }

        internal static string AccountIdLabel
        {
            get
            {
                return ResourceManager.GetString("AccountIdLabel", resourceCulture);
            }
        }

        internal static string AccountIdPlaceholder
        {
            get
            {
                return ResourceManager.GetString("AccountIdPlaceholder", resourceCulture);
            }
        }

        internal static string AccountTokenLabel
        {
            get
            {
                return ResourceManager.GetString("AccountTokenLabel", resourceCulture);
            }
        }

        internal static string AccountTokenPlaceholder
        {
            get
            {
                return ResourceManager.GetString("AccountTokenPlaceholder", resourceCulture);
            }
        }

        internal static string TerminalIdLabel
        {
            get
            {
                return ResourceManager.GetString("TerminalIdLabel", resourceCulture);
            }
        }

        internal static string TerminalIdPlaceholder
        {
            get
            {
                return ResourceManager.GetString("TerminalIdPlaceholder", resourceCulture);
            }
        }

        internal static string ArePartialApprovalsAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("ArePartialApprovalsAllowedLabel", resourceCulture);
            }
        }

        internal static string AreDuplicateTransactionsAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("AreDuplicateTransactionsAllowedLabel", resourceCulture);
            }
        }

        internal static string IsCashbackAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("IsCashbackAllowedLabel", resourceCulture);
            }
        }

        internal static string CashbackAmountLabel
        {
            get
            {
                return ResourceManager.GetString("CashbackAmountLabel", resourceCulture);
            }
        }

        internal static string CashbackAmountPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("CashbackAmountPlaceHolder", resourceCulture);
            }
        }

        internal static string IsDebitAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("IsDebitAllowedLabel", resourceCulture);
            }
        }

        internal static string IsEmvAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("IsEmvAllowedLabel", resourceCulture);
            }
        }

        internal static string POSIdLabel
        {
            get
            {
                return ResourceManager.GetString("POSIdLabel", resourceCulture);
            }
        }

        internal static string POSIdPlaceholder
        {
            get
            {
                return ResourceManager.GetString("POSIdPlaceholder", resourceCulture);
            }
        }

        internal static string EftposAddressLabel
        {
            get
            {
                return ResourceManager.GetString("EftposAddressLabel", resourceCulture);
            }
        }

        internal static string EftposAddressPlaceholder
        {
            get
            {
                return ResourceManager.GetString("EftposAddressPlaceholder", resourceCulture);
            }
        }

        internal static string IsAllowPrintOnEFTPOSLabel
        {
            get
            {
                return ResourceManager.GetString("IsAllowPrintOnEFTPOSLabel", resourceCulture);
            }
        }

        internal static string EncKeyLabel
        {
            get
            {
                return ResourceManager.GetString("EncKeyLabel", resourceCulture);
            }
        }

        internal static string EncKeyPlaceholder
        {
            get
            {
                return ResourceManager.GetString("EncKeyPlaceholder", resourceCulture);
            }
        }

        internal static string HmacKeyLabel
        {
            get
            {
                return ResourceManager.GetString("HmacKeyLabel", resourceCulture);
            }
        }

        internal static string HmacKeyPlaceholder
        {
            get
            {
                return ResourceManager.GetString("HmacKeyPlaceholder", resourceCulture);
            }
        }

        internal static string POSummaryText
        {
            get
            {
                return ResourceManager.GetString("POSummaryText", resourceCulture);
            }
        }

        internal static string CreateDraftPOButtonText
        {
            get
            {
                return ResourceManager.GetString("CreateDraftPOButtonText", resourceCulture);
            }
        }

        internal static string OrderItemTitleText
        {
            get
            {
                return ResourceManager.GetString("OrderItemTitleText", resourceCulture);
            }
        }

        internal static string SuppliersTitleText
        {
            get
            {
                return ResourceManager.GetString("SuppliersTitleText", resourceCulture);
            }
        }

        internal static string CreatePOText
        {
            get
            {
                return ResourceManager.GetString("CreatePOText", resourceCulture);
            }
        }

        internal static string POCreatedText
        {
            get
            {
                return ResourceManager.GetString("POCreatedText", resourceCulture);
            }
        }

        internal static string DOB
        {
            get
            {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }

        internal static string LoyaltyPoints
        {
            get
            {
                return ResourceManager.GetString("LoyaltyPoints", resourceCulture);
            }
        }

        internal static string CreditBalance
        {
            get
            {
                return ResourceManager.GetString("CreditBalance", resourceCulture);
            }
        }

        internal static string AvgPurchase
        {
            get
            {
                return ResourceManager.GetString("AvgPurchase", resourceCulture);
            }
        }

        internal static string TotalPurchase
        {
            get
            {
                return ResourceManager.GetString("TotalPurchase", resourceCulture);
            }
        }

        internal static string VisitThisMonth
        {
            get
            {
                return ResourceManager.GetString("VisitThisMonth", resourceCulture);
            }
        }

        internal static string AvgMonthlyVisits
        {
            get
            {
                return ResourceManager.GetString("AvgMonthlyVisits", resourceCulture);
            }
        }

        internal static string StockOfflineText
        {
            get
            {
                return ResourceManager.GetString("StockOfflineText", resourceCulture);
            }
        }

        internal static string PrintValidation
        {
            get
            {
                return ResourceManager.GetString("PrintValidation", resourceCulture);
            }
        }

        internal static string MintResetPin
        {
            get
            {
                return ResourceManager.GetString("MintResetPin", resourceCulture);
            }
        }

        internal static string MintResetPinSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("MintResetPinSuccessMessage", resourceCulture);
            }
        }

        internal static string ForgotPin_ButtonText
        {
            get
            {
                return ResourceManager.GetString("ForgotPin_ButtonText", resourceCulture);
            }
        }

        internal static string StoreCredit_ButtonText
        {
            get
            {
                return ResourceManager.GetString("StoreCredit_ButtonText", resourceCulture);
            }
        }

        internal static string IssueCustomerStoreCredit_Text
        {
            get
            {
                return ResourceManager.GetString("IssueCustomerStoreCredit_Text", resourceCulture);
            }
        }

        internal static string StoreCreditValue_Text
        {
            get
            {
                return ResourceManager.GetString("StoreCreditValue_Text", resourceCulture);
            }
        }

        internal static string IssueStoreCredit_Text
        {
            get
            {
                return ResourceManager.GetString("IssueStoreCredit_Text", resourceCulture);
            }
        }

        internal static string IsReStockWhenRefundText
        {
            get
            {
                return ResourceManager.GetString("IsReStockWhenRefundText", resourceCulture);
            }
        }

        internal static string AddGiftCardText
        {
            get
            {
                return ResourceManager.GetString("AddGiftCardText", resourceCulture);
            }
        }

        internal static string ParkThisSaleText
        {
            get
            {
                return ResourceManager.GetString("ParkThisSaleText", resourceCulture);
            }
        }

        internal static string OpenCashDrawerText
        {
            get
            {
                return ResourceManager.GetString("OpenCashDrawerText", resourceCulture);
            }
        }

        internal static string DiscardText
        {
            get
            {
                return ResourceManager.GetString("DiscardText", resourceCulture);
            }
        }

        internal static string ReopenInvoiceAlertMessage
        {
            get
            {
                return ResourceManager.GetString("ReopenInvoiceAlertMessage", resourceCulture);
            }
        }

        internal static string RefundInvoiceAlertMessage
        {
            get
            {
                return ResourceManager.GetString("RefundInvoiceAlertMessage", resourceCulture);
            }
        }

        internal static string RegisterOpenAlertMessage
        {
            get
            {
                return ResourceManager.GetString("RegisterOpenAlertMessage", resourceCulture);
            }
        }

        internal static string DenominationAddButtonText
        {
            get
            {
                return ResourceManager.GetString("DenominationAddButtonText", resourceCulture);
            }
        }

        internal static string RemoveCustomerText
        {
            get
            {
                return ResourceManager.GetString("RemoveCustomerText", resourceCulture);
            }
        }


        internal static string AverageSaleValueText
        {
            get
            {
                return ResourceManager.GetString("AverageSaleValueText", resourceCulture);
            }
        }

        internal static string NumberOfTransactionsText
        {
            get
            {
                return ResourceManager.GetString("NumberOfTransactionsText", resourceCulture);
            }
        }

        internal static string NewCustomersText
        {
            get
            {
                return ResourceManager.GetString("NewCustomersText", resourceCulture);
            }
        }

    }
}